%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'flm_base';
M_.dynare_version = '5.1';
oo_.dynare_version = '5.1';
options_.dynare_version = '5.1';
%
% Some global variables initialization
%
global_initialization;
options_.nograph = true;
M_.exo_names = cell(5,1);
M_.exo_names_tex = cell(5,1);
M_.exo_names_long = cell(5,1);
M_.exo_names(1) = {'EZ'};
M_.exo_names_tex(1) = {'EZ'};
M_.exo_names_long(1) = {'EZ'};
M_.exo_names(2) = {'EOMEGA'};
M_.exo_names_tex(2) = {'EOMEGA'};
M_.exo_names_long(2) = {'EOMEGA'};
M_.exo_names(3) = {'EA'};
M_.exo_names_tex(3) = {'EA'};
M_.exo_names_long(3) = {'EA'};
M_.exo_names(4) = {'EG'};
M_.exo_names_tex(4) = {'EG'};
M_.exo_names_long(4) = {'EG'};
M_.exo_names(5) = {'EERR'};
M_.exo_names_tex(5) = {'EERR'};
M_.exo_names_long(5) = {'EERR'};
M_.endo_names = cell(32,1);
M_.endo_names_tex = cell(32,1);
M_.endo_names_long = cell(32,1);
M_.endo_names(1) = {'NTY'};
M_.endo_names_tex(1) = {'NTY'};
M_.endo_names_long(1) = {'NTY'};
M_.endo_names(2) = {'NY'};
M_.endo_names_tex(2) = {'NY'};
M_.endo_names_long(2) = {'NY'};
M_.endo_names(3) = {'NC'};
M_.endo_names_tex(3) = {'NC'};
M_.endo_names_long(3) = {'NC'};
M_.endo_names(4) = {'NQ'};
M_.endo_names_tex(4) = {'NQ'};
M_.endo_names_long(4) = {'NQ'};
M_.endo_names(5) = {'NOY'};
M_.endo_names_tex(5) = {'NOY'};
M_.endo_names_long(5) = {'NOY'};
M_.endo_names(6) = {'NR'};
M_.endo_names_tex(6) = {'NR'};
M_.endo_names_long(6) = {'NR'};
M_.endo_names(7) = {'G'};
M_.endo_names_tex(7) = {'G'};
M_.endo_names_long(7) = {'G'};
M_.endo_names(8) = {'NCY'};
M_.endo_names_tex(8) = {'NCY'};
M_.endo_names_long(8) = {'NCY'};
M_.endo_names(9) = {'NOC'};
M_.endo_names_tex(9) = {'NOC'};
M_.endo_names_long(9) = {'NOC'};
M_.endo_names(10) = {'NPI'};
M_.endo_names_tex(10) = {'NPI'};
M_.endo_names_long(10) = {'NPI'};
M_.endo_names(11) = {'NPIY'};
M_.endo_names_tex(11) = {'NPIY'};
M_.endo_names_long(11) = {'NPIY'};
M_.endo_names(12) = {'DD'};
M_.endo_names_tex(12) = {'DD'};
M_.endo_names_long(12) = {'DD'};
M_.endo_names(13) = {'NN'};
M_.endo_names_tex(13) = {'NN'};
M_.endo_names_long(13) = {'NN'};
M_.endo_names(14) = {'NMC'};
M_.endo_names_tex(14) = {'NMC'};
M_.endo_names_long(14) = {'NMC'};
M_.endo_names(15) = {'DELTA'};
M_.endo_names_tex(15) = {'DELTA'};
M_.endo_names_long(15) = {'DELTA'};
M_.endo_names(16) = {'NWP'};
M_.endo_names_tex(16) = {'NWP'};
M_.endo_names_long(16) = {'NWP'};
M_.endo_names(17) = {'NA'};
M_.endo_names_tex(17) = {'NA'};
M_.endo_names_long(17) = {'NA'};
M_.endo_names(18) = {'NL'};
M_.endo_names_tex(18) = {'NL'};
M_.endo_names_long(18) = {'NL'};
M_.endo_names(19) = {'NO'};
M_.endo_names_tex(19) = {'NO'};
M_.endo_names_long(19) = {'NO'};
M_.endo_names(20) = {'NX'};
M_.endo_names_tex(20) = {'NX'};
M_.endo_names_long(20) = {'NX'};
M_.endo_names(21) = {'NZ'};
M_.endo_names_tex(21) = {'NZ'};
M_.endo_names_long(21) = {'NZ'};
M_.endo_names(22) = {'NETA'};
M_.endo_names_tex(22) = {'NETA'};
M_.endo_names_long(22) = {'NETA'};
M_.endo_names(23) = {'Z'};
M_.endo_names_tex(23) = {'Z'};
M_.endo_names_long(23) = {'Z'};
M_.endo_names(24) = {'OMEGA'};
M_.endo_names_tex(24) = {'OMEGA'};
M_.endo_names_long(24) = {'OMEGA'};
M_.endo_names(25) = {'A'};
M_.endo_names_tex(25) = {'A'};
M_.endo_names_long(25) = {'A'};
M_.endo_names(26) = {'ERR'};
M_.endo_names_tex(26) = {'ERR'};
M_.endo_names_long(26) = {'ERR'};
M_.endo_names(27) = {'WELF'};
M_.endo_names_tex(27) = {'WELF'};
M_.endo_names_long(27) = {'WELF'};
M_.endo_names(28) = {'NPE'};
M_.endo_names_tex(28) = {'NPE'};
M_.endo_names_long(28) = {'NPE'};
M_.endo_names(29) = {'RER'};
M_.endo_names_tex(29) = {'RER'};
M_.endo_names_long(29) = {'RER'};
M_.endo_names(30) = {'TPE'};
M_.endo_names_tex(30) = {'TPE'};
M_.endo_names_long(30) = {'TPE'};
M_.endo_names(31) = {'OBJQ'};
M_.endo_names_tex(31) = {'OBJQ'};
M_.endo_names_long(31) = {'OBJQ'};
M_.endo_names(32) = {'MRKQ'};
M_.endo_names_tex(32) = {'MRKQ'};
M_.endo_names_long(32) = {'MRKQ'};
M_.endo_partitions = struct();
M_.param_names = cell(32,1);
M_.param_names_tex = cell(32,1);
M_.param_names_long = cell(32,1);
M_.param_names(1) = {'GAMMA'};
M_.param_names_tex(1) = {'GAMMA'};
M_.param_names_long(1) = {'GAMMA'};
M_.param_names(2) = {'ALPHA'};
M_.param_names_tex(2) = {'ALPHA'};
M_.param_names_long(2) = {'ALPHA'};
M_.param_names(3) = {'NU'};
M_.param_names_tex(3) = {'NU'};
M_.param_names_long(3) = {'NU'};
M_.param_names(4) = {'PHI_HEAD'};
M_.param_names_tex(4) = {'PHI\_HEAD'};
M_.param_names_long(4) = {'PHI_HEAD'};
M_.param_names(5) = {'PHI_CORE'};
M_.param_names_tex(5) = {'PHI\_CORE'};
M_.param_names_long(5) = {'PHI_CORE'};
M_.param_names(6) = {'PHI_COMM'};
M_.param_names_tex(6) = {'PHI\_COMM'};
M_.param_names_long(6) = {'PHI_COMM'};
M_.param_names(7) = {'RHO_Z'};
M_.param_names_tex(7) = {'RHO\_Z'};
M_.param_names_long(7) = {'RHO_Z'};
M_.param_names(8) = {'RHO_OMEGA'};
M_.param_names_tex(8) = {'RHO\_OMEGA'};
M_.param_names_long(8) = {'RHO_OMEGA'};
M_.param_names(9) = {'RHO_A'};
M_.param_names_tex(9) = {'RHO\_A'};
M_.param_names_long(9) = {'RHO_A'};
M_.param_names(10) = {'RHO_ERR'};
M_.param_names_tex(10) = {'RHO\_ERR'};
M_.param_names_long(10) = {'RHO_ERR'};
M_.param_names(11) = {'SZ'};
M_.param_names_tex(11) = {'SZ'};
M_.param_names_long(11) = {'SZ'};
M_.param_names(12) = {'SOMEGA'};
M_.param_names_tex(12) = {'SOMEGA'};
M_.param_names_long(12) = {'SOMEGA'};
M_.param_names(13) = {'SA'};
M_.param_names_tex(13) = {'SA'};
M_.param_names_long(13) = {'SA'};
M_.param_names(14) = {'SERR'};
M_.param_names_tex(14) = {'SERR'};
M_.param_names_long(14) = {'SERR'};
M_.param_names(15) = {'ES'};
M_.param_names_tex(15) = {'ES'};
M_.param_names_long(15) = {'ES'};
M_.param_names(16) = {'EPS'};
M_.param_names_tex(16) = {'EPS'};
M_.param_names_long(16) = {'EPS'};
M_.param_names(17) = {'BETA'};
M_.param_names_tex(17) = {'BETA'};
M_.param_names_long(17) = {'BETA'};
M_.param_names(18) = {'THETA'};
M_.param_names_tex(18) = {'THETA'};
M_.param_names_long(18) = {'THETA'};
M_.param_names(19) = {'ZS'};
M_.param_names_tex(19) = {'ZS'};
M_.param_names_long(19) = {'ZS'};
M_.param_names(20) = {'AS'};
M_.param_names_tex(20) = {'AS'};
M_.param_names_long(20) = {'AS'};
M_.param_names(21) = {'RHO_G'};
M_.param_names_tex(21) = {'RHO\_G'};
M_.param_names_long(21) = {'RHO_G'};
M_.param_names(22) = {'SG'};
M_.param_names_tex(22) = {'SG'};
M_.param_names_long(22) = {'SG'};
M_.param_names(23) = {'PHI_BENCH'};
M_.param_names_tex(23) = {'PHI\_BENCH'};
M_.param_names_long(23) = {'PHI_BENCH'};
M_.param_names(24) = {'PHI_NAT'};
M_.param_names_tex(24) = {'PHI\_NAT'};
M_.param_names_long(24) = {'PHI_NAT'};
M_.param_names(25) = {'PHI_EFF'};
M_.param_names_tex(25) = {'PHI\_EFF'};
M_.param_names_long(25) = {'PHI_EFF'};
M_.param_names(26) = {'PHI_Y'};
M_.param_names_tex(26) = {'PHI\_Y'};
M_.param_names_long(26) = {'PHI_Y'};
M_.param_names(27) = {'PHI_Yn'};
M_.param_names_tex(27) = {'PHI\_Yn'};
M_.param_names_long(27) = {'PHI_Yn'};
M_.param_names(28) = {'PHI_Yfe'};
M_.param_names_tex(28) = {'PHI\_Yfe'};
M_.param_names_long(28) = {'PHI_Yfe'};
M_.param_names(29) = {'MRKss'};
M_.param_names_tex(29) = {'MRKss'};
M_.param_names_long(29) = {'MRKss'};
M_.param_names(30) = {'Q_COMM'};
M_.param_names_tex(30) = {'Q\_COMM'};
M_.param_names_long(30) = {'Q_COMM'};
M_.param_names(31) = {'Q_Y'};
M_.param_names_tex(31) = {'Q\_Y'};
M_.param_names_long(31) = {'Q_Y'};
M_.param_names(32) = {'Q_RER'};
M_.param_names_tex(32) = {'Q\_RER'};
M_.param_names_long(32) = {'Q_RER'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 5;
M_.endo_nbr = 32;
M_.param_nbr = 32;
M_.orig_endo_nbr = 32;
M_.aux_vars = [];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(5, 5);
M_.Correlation_matrix = eye(5, 5);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.nonzero_hessian_eqs = [1 2 3 4 5 6 7 8 9 10 11 12 13 15 16 17 18 19 25 26 27 28 29 30 31 32];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.orig_eq_nbr = 32;
M_.eq_nbr = 32;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 9 0;
 1 10 0;
 0 11 41;
 2 12 0;
 0 13 0;
 0 14 0;
 3 15 42;
 0 16 0;
 0 17 0;
 0 18 43;
 0 19 44;
 0 20 45;
 0 21 46;
 0 22 0;
 4 23 0;
 0 24 0;
 0 25 0;
 0 26 0;
 0 27 0;
 0 28 0;
 0 29 0;
 0 30 0;
 5 31 0;
 6 32 0;
 7 33 0;
 8 34 0;
 0 35 47;
 0 36 0;
 0 37 0;
 0 38 48;
 0 39 0;
 0 40 0;]';
M_.nstatic = 17;
M_.nfwrd   = 7;
M_.npred   = 7;
M_.nboth   = 1;
M_.nsfwrd   = 8;
M_.nspred   = 8;
M_.ndynamic   = 15;
M_.dynamic_tmp_nbr = [34; 44; 9; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , '1' ;
  2 , 'name' , '2' ;
  3 , 'name' , 'NC' ;
  4 , 'name' , '4' ;
  5 , 'name' , 'NPI' ;
  6 , 'name' , 'DD' ;
  7 , 'name' , 'NN' ;
  8 , 'name' , '8' ;
  9 , 'name' , 'DELTA' ;
  10 , 'name' , 'NMC' ;
  11 , 'name' , 'NWP' ;
  12 , 'name' , 'NL' ;
  13 , 'name' , 'NR' ;
  14 , 'name' , 'NO' ;
  15 , 'name' , 'NOC' ;
  16 , 'name' , 'NOY' ;
  17 , 'name' , 'NX' ;
  18 , 'name' , '18' ;
  19 , 'name' , 'NETA' ;
  20 , 'name' , 'Z' ;
  21 , 'name' , 'OMEGA' ;
  22 , 'name' , 'A' ;
  23 , 'name' , 'ERR' ;
  24 , 'name' , 'G' ;
  25 , 'name' , '25' ;
  26 , 'name' , '26' ;
  27 , 'name' , 'WELF' ;
  28 , 'name' , 'NPE' ;
  29 , 'name' , 'RER' ;
  30 , 'name' , 'TPE' ;
  31 , 'name' , 'OBJQ' ;
  32 , 'name' , 'MRKQ' ;
};
M_.mapping.NTY.eqidx = [1 4 ];
M_.mapping.NY.eqidx = [1 6 7 12 13 16 17 32 ];
M_.mapping.NC.eqidx = [1 2 3 6 7 11 15 27 29 ];
M_.mapping.NQ.eqidx = [1 4 5 10 13 15 16 17 18 28 31 32 ];
M_.mapping.NOY.eqidx = [1 14 16 ];
M_.mapping.NR.eqidx = [2 13 ];
M_.mapping.G.eqidx = [2 24 27 ];
M_.mapping.NCY.eqidx = [3 ];
M_.mapping.NOC.eqidx = [3 14 15 ];
M_.mapping.NPI.eqidx = [2 5 13 ];
M_.mapping.NPIY.eqidx = [5 6 7 8 9 13 ];
M_.mapping.DD.eqidx = [6 8 9 ];
M_.mapping.NN.eqidx = [7 8 9 ];
M_.mapping.NMC.eqidx = [7 10 12 16 ];
M_.mapping.DELTA.eqidx = [9 12 16 ];
M_.mapping.NWP.eqidx = [10 11 12 ];
M_.mapping.NA.eqidx = [10 25 ];
M_.mapping.NL.eqidx = [11 12 27 ];
M_.mapping.NO.eqidx = [14 19 28 ];
M_.mapping.NX.eqidx = [14 17 19 ];
M_.mapping.NZ.eqidx = [17 18 26 28 ];
M_.mapping.NETA.eqidx = [18 19 ];
M_.mapping.Z.eqidx = [20 26 ];
M_.mapping.OMEGA.eqidx = [17 21 ];
M_.mapping.A.eqidx = [22 25 ];
M_.mapping.ERR.eqidx = [13 23 ];
M_.mapping.WELF.eqidx = [27 ];
M_.mapping.NPE.eqidx = [28 29 30 ];
M_.mapping.RER.eqidx = [29 30 32 ];
M_.mapping.TPE.eqidx = [30 ];
M_.mapping.OBJQ.eqidx = [31 ];
M_.mapping.MRKQ.eqidx = [18 32 ];
M_.mapping.EZ.eqidx = [20 ];
M_.mapping.EOMEGA.eqidx = [21 ];
M_.mapping.EA.eqidx = [22 ];
M_.mapping.EG.eqidx = [24 ];
M_.mapping.EERR.eqidx = [23 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [2 4 7 15 23 24 25 26 ];
M_.exo_names_orig_ord = [1:5];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(32, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(5, 1);
M_.params = NaN(32, 1);
M_.endo_trends = struct('deflator', cell(32, 1), 'log_deflator', cell(32, 1), 'growth_factor', cell(32, 1), 'log_growth_factor', cell(32, 1));
M_.NNZDerivatives = [124; 232; -1; ];
M_.static_tmp_nbr = [23; 5; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(1) = 0.2;
GAMMA = M_.params(1);
M_.params(2) = 0.2;
ALPHA = M_.params(2);
M_.params(3) = 0.5;
NU = M_.params(3);
M_.params(16) = 7.67;
EPS = M_.params(16);
M_.params(17) = 0.99;
BETA = M_.params(17);
M_.params(18) = 0.75;
THETA = M_.params(18);
M_.params(4) = 0;
PHI_HEAD = M_.params(4);
M_.params(5) = 1.5;
PHI_CORE = M_.params(5);
M_.params(6) = 0.00;
PHI_COMM = M_.params(6);
M_.params(27) = 0.0;
PHI_Yn = M_.params(27);
M_.params(28) = 0.0;
PHI_Yfe = M_.params(28);
M_.params(26) = 0.0;
PHI_Y = M_.params(26);
M_.params(23) = 0;
PHI_BENCH = M_.params(23);
M_.params(24) = 0;
PHI_NAT = M_.params(24);
M_.params(25) = 1;
PHI_EFF = M_.params(25);
M_.params(20) = 1;
AS = M_.params(20);
M_.params(19) = 1;
ZS = M_.params(19);
M_.params(15) = 0.01;
ES = M_.params(15);
M_.params(7) = 0.5;
RHO_Z = M_.params(7);
M_.params(8) = 0.5;
RHO_OMEGA = M_.params(8);
M_.params(9) = 0.95;
RHO_A = M_.params(9);
M_.params(21) = 0.5;
RHO_G = M_.params(21);
M_.params(10) = 0.5;
RHO_ERR = M_.params(10);
M_.params(11) = 0.01;
SZ = M_.params(11);
M_.params(12) = 0.01;
SOMEGA = M_.params(12);
M_.params(13) = 0.01;
SA = M_.params(13);
M_.params(22) = 0.01;
SG = M_.params(22);
M_.params(14) = 0.01;
SERR = M_.params(14);
M_.params(29) = 1;
MRKss = M_.params(29);
M_.params(30) = 0;
Q_COMM = M_.params(30);
M_.params(31) = 0;
Q_Y = M_.params(31);
M_.params(32) = 0;
Q_RER = M_.params(32);
steady;
oo_.dr.eigval = check(M_,options_,oo_);
model_diagnostics(M_,options_,oo_);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (M_.params(11))^2;
M_.Sigma_e(2, 2) = (M_.params(12))^2;
M_.Sigma_e(3, 3) = (M_.params(13))^2;
M_.Sigma_e(4, 4) = (M_.params(22))^2;
M_.Sigma_e(5, 5) = (M_.params(14))^2;
options_.ar = 0;
options_.irf = 0;
options_.nograph = true;
options_.noprint = true;
options_.order = 2;
options_.pruning = true;
var_list_ = {};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'flm_base_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'flm_base_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'flm_base_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'flm_base_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'flm_base_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'flm_base_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'flm_base_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
