%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'ABK2016';
M_.dynare_version = '5.1';
oo_.dynare_version = '5.1';
options_.dynare_version = '5.1';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(4,1);
M_.exo_names_tex = cell(4,1);
M_.exo_names_long = cell(4,1);
M_.exo_names(1) = {'varepsilon_R'};
M_.exo_names_tex(1) = {'\varepsilon^{R}'};
M_.exo_names_long(1) = {'shock process for domestic interest rate'};
M_.exo_names(2) = {'varepsilon_A'};
M_.exo_names_tex(2) = {'\varepsilon^{A}'};
M_.exo_names_long(2) = {'shock process for TFP'};
M_.exo_names(3) = {'varepsilon_Rstar'};
M_.exo_names_tex(3) = {'\varepsilon^{R*}'};
M_.exo_names_long(3) = {'shock process for foreign interest rate'};
M_.exo_names(4) = {'varepsilon_Ystar'};
M_.exo_names_tex(4) = {'\varepsilon^{Y*}'};
M_.exo_names_long(4) = {'shock process for foreign income'};
M_.endo_names = cell(33,1);
M_.endo_names_tex = cell(33,1);
M_.endo_names_long = cell(33,1);
M_.endo_names(1) = {'mc'};
M_.endo_names_tex(1) = {'mc'};
M_.endo_names_long(1) = {'marginal cost'};
M_.endo_names(2) = {'Pi'};
M_.endo_names_tex(2) = {'\Pi'};
M_.endo_names_long(2) = {'gross inflation'};
M_.endo_names(3) = {'Z'};
M_.endo_names_tex(3) = {'Z'};
M_.endo_names_long(3) = {'rental price of capital'};
M_.endo_names(4) = {'w'};
M_.endo_names_tex(4) = {'w'};
M_.endo_names_long(4) = {'real wages'};
M_.endo_names(5) = {'R'};
M_.endo_names_tex(5) = {'R'};
M_.endo_names_long(5) = {'gross real interest rate'};
M_.endo_names(6) = {'epsilon'};
M_.endo_names_tex(6) = {'\epsilon'};
M_.endo_names_long(6) = {'real exchange rate'};
M_.endo_names(7) = {'Q'};
M_.endo_names_tex(7) = {'Q'};
M_.endo_names_long(7) = {'equity price'};
M_.endo_names(8) = {'Y'};
M_.endo_names_tex(8) = {'Y'};
M_.endo_names_long(8) = {'output'};
M_.endo_names(9) = {'M'};
M_.endo_names_tex(9) = {'M'};
M_.endo_names_long(9) = {'imports'};
M_.endo_names(10) = {'L'};
M_.endo_names_tex(10) = {'L'};
M_.endo_names_long(10) = {'labour supply'};
M_.endo_names(11) = {'C'};
M_.endo_names_tex(11) = {'C'};
M_.endo_names_long(11) = {'consumption'};
M_.endo_names(12) = {'I'};
M_.endo_names_tex(12) = {'I'};
M_.endo_names_long(12) = {'investment'};
M_.endo_names(13) = {'K'};
M_.endo_names_tex(13) = {'K'};
M_.endo_names_long(13) = {'capital stock'};
M_.endo_names(14) = {'EX'};
M_.endo_names_tex(14) = {'EX'};
M_.endo_names_long(14) = {'exports'};
M_.endo_names(15) = {'N'};
M_.endo_names_tex(15) = {'N'};
M_.endo_names_long(15) = {'net worth'};
M_.endo_names(16) = {'K_b'};
M_.endo_names_tex(16) = {'K^{b}'};
M_.endo_names_long(16) = {'bank capital'};
M_.endo_names(17) = {'K_h'};
M_.endo_names_tex(17) = {'K^{h}'};
M_.endo_names_long(17) = {'household capital'};
M_.endo_names(18) = {'D'};
M_.endo_names_tex(18) = {'D'};
M_.endo_names_long(18) = {'domestic deposits'};
M_.endo_names(19) = {'D_star'};
M_.endo_names_tex(19) = {'D^{*}'};
M_.endo_names_long(19) = {'foreign deposits'};
M_.endo_names(20) = {'x'};
M_.endo_names_tex(20) = {'x'};
M_.endo_names_long(20) = {'fraction of assets financed by foreign borrowing'};
M_.endo_names(21) = {'psi'};
M_.endo_names_tex(21) = {'\psi'};
M_.endo_names_long(21) = {'Tobin Q ratio of the bank'};
M_.endo_names(22) = {'phi'};
M_.endo_names_tex(22) = {'\phi'};
M_.endo_names_long(22) = {'leverage multiple (Qk/n)'};
M_.endo_names(23) = {'upsilon'};
M_.endo_names_tex(23) = {'\upsilon'};
M_.endo_names_long(23) = {'marginal cost of deposits'};
M_.endo_names(24) = {'mu'};
M_.endo_names_tex(24) = {'\mu'};
M_.endo_names_long(24) = {'excess return on capital over home deposits'};
M_.endo_names(25) = {'mu_star'};
M_.endo_names_tex(25) = {'\mu^{*}'};
M_.endo_names_long(25) = {'cost advantage of foreign currency debt over home deposits'};
M_.endo_names(26) = {'A'};
M_.endo_names_tex(26) = {'A'};
M_.endo_names_long(26) = {'total factor productivity'};
M_.endo_names(27) = {'R_star'};
M_.endo_names_tex(27) = {'R^{*}'};
M_.endo_names_long(27) = {'foreign gross interest rate'};
M_.endo_names(28) = {'Y_star'};
M_.endo_names_tex(28) = {'Y^{*}'};
M_.endo_names_long(28) = {'foreign income'};
M_.endo_names(29) = {'Phi'};
M_.endo_names_tex(29) = {'\Phi'};
M_.endo_names_long(29) = {'investment cost of adjustment'};
M_.endo_names(30) = {'Theta'};
M_.endo_names_tex(30) = {'\Theta(x_{t})'};
M_.endo_names_long(30) = {'fraction of banker assets diverted'};
M_.endo_names(31) = {'chi_h'};
M_.endo_names_tex(31) = {'\chi^{h}'};
M_.endo_names_long(31) = {'worker extra management cost of buying equity'};
M_.endo_names(32) = {'chi_b'};
M_.endo_names_tex(32) = {'\chi^{b}'};
M_.endo_names_long(32) = {'cost of borrowing from foreigners'};
M_.endo_names(33) = {'Ynet'};
M_.endo_names_tex(33) = {'Y^{net}'};
M_.endo_names_long(33) = {'net output'};
M_.endo_partitions = struct();
M_.param_names = cell(27,1);
M_.param_names_tex = cell(27,1);
M_.param_names_long = cell(27,1);
M_.param_names(1) = {'theta'};
M_.param_names_tex(1) = {'\theta'};
M_.param_names_long(1) = {'elasticity of leverage wrt foreign borrowing'};
M_.param_names(2) = {'theta_0'};
M_.param_names_tex(2) = {'\theta_{0}'};
M_.param_names_long(2) = {'home bias in funding'};
M_.param_names(3) = {'sigma'};
M_.param_names_tex(3) = {'\sigma'};
M_.param_names_long(3) = {'survival probability'};
M_.param_names(4) = {'xi'};
M_.param_names_tex(4) = {'\xi'};
M_.param_names_long(4) = {'fraction of total assets brought by new banks'};
M_.param_names(5) = {'varkappa_b'};
M_.param_names_tex(5) = {'\varkappa^{b}'};
M_.param_names_long(5) = {'management cost for foreign borrowing'};
M_.param_names(6) = {'betta'};
M_.param_names_tex(6) = {'\beta'};
M_.param_names_long(6) = {'discount rate'};
M_.param_names(7) = {'zeta'};
M_.param_names_tex(7) = {'\zeta'};
M_.param_names_long(7) = {'inverse of Frisch elasticity of labour supply'};
M_.param_names(8) = {'zeta_0'};
M_.param_names_tex(8) = {'\zeta_{0}'};
M_.param_names_long(8) = {'inverse of labour supply capacity'};
M_.param_names(9) = {'varkappa_h'};
M_.param_names_tex(9) = {'\varkappa_{h}'};
M_.param_names_long(9) = {'cost parameter of direct finance'};
M_.param_names(10) = {'alphha_K'};
M_.param_names_tex(10) = {'\alpha_{K}'};
M_.param_names_long(10) = {'cost share of capital'};
M_.param_names(11) = {'alphha_M'};
M_.param_names_tex(11) = {'\alpha_{M}'};
M_.param_names_long(11) = {'cost share of imported intermediate goods'};
M_.param_names(12) = {'lambda'};
M_.param_names_tex(12) = {'\lambda'};
M_.param_names_long(12) = {'one minus the depreciation rate'};
M_.param_names(13) = {'eta'};
M_.param_names_tex(13) = {'\eta'};
M_.param_names_long(13) = {'elasticity of demand'};
M_.param_names(14) = {'omega'};
M_.param_names_tex(14) = {'\omega'};
M_.param_names_long(14) = {'pins down kappa (slope of NKPC)'};
M_.param_names(15) = {'kappa_I'};
M_.param_names_tex(15) = {'\kappa_{I}'};
M_.param_names_long(15) = {'cost of adjusting investment goods production'};
M_.param_names(16) = {'varphi'};
M_.param_names_tex(16) = {'\varphi'};
M_.param_names_long(16) = {'price elasticity of export demand'};
M_.param_names(17) = {'kappa'};
M_.param_names_tex(17) = {'\kappa'};
M_.param_names_long(17) = {'slope of NKPC'};
M_.param_names(18) = {'A_ss'};
M_.param_names_tex(18) = {'\bar{A}'};
M_.param_names_long(18) = {'steady state productivity'};
M_.param_names(19) = {'rho_i'};
M_.param_names_tex(19) = {'\rho_{i}'};
M_.param_names_long(19) = {'Taylor rule persistence'};
M_.param_names(20) = {'omega_pi'};
M_.param_names_tex(20) = {'\omega_{\pi}'};
M_.param_names_long(20) = {'Taylor rule response to inflation'};
M_.param_names(21) = {'rho_A'};
M_.param_names_tex(21) = {'\rho_{A}'};
M_.param_names_long(21) = {'TFP persistence'};
M_.param_names(22) = {'rho_Rstar'};
M_.param_names_tex(22) = {'\rho_{R*}'};
M_.param_names_long(22) = {'foreign interest rate persistence'};
M_.param_names(23) = {'rho_Ystar'};
M_.param_names_tex(23) = {'\rho_{Y*}'};
M_.param_names_long(23) = {'foreign income persistence'};
M_.param_names(24) = {'sigma_i'};
M_.param_names_tex(24) = {'\sigma_{i}'};
M_.param_names_long(24) = {'standard deviation of interest rate shock'};
M_.param_names(25) = {'sigma_istar'};
M_.param_names_tex(25) = {'\sigma_{i*}'};
M_.param_names_long(25) = {'standard deviation of foreign interest rate shock'};
M_.param_names(26) = {'sigma_A'};
M_.param_names_tex(26) = {'\sigma_{A}'};
M_.param_names_long(26) = {'standard deviation of TFP shock'};
M_.param_names(27) = {'sigma_Ystar'};
M_.param_names_tex(27) = {'\sigma_{Y*}'};
M_.param_names_long(27) = {'standard deviation of foreign income shock'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 4;
M_.endo_nbr = 33;
M_.param_nbr = 27;
M_.orig_endo_nbr = 33;
M_.aux_vars = [];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(4, 4);
M_.Correlation_matrix = eye(4, 4);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.orig_eq_nbr = 33;
M_.eq_nbr = 33;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 9 0;
 0 10 42;
 0 11 43;
 0 12 0;
 1 13 0;
 0 14 44;
 0 15 45;
 0 16 46;
 0 17 0;
 0 18 47;
 0 19 48;
 0 20 0;
 2 21 0;
 0 22 0;
 0 23 0;
 3 24 0;
 0 25 0;
 4 26 0;
 5 27 0;
 0 28 0;
 0 29 49;
 0 30 0;
 0 31 0;
 0 32 0;
 0 33 0;
 6 34 0;
 7 35 0;
 8 36 0;
 0 37 0;
 0 38 0;
 0 39 0;
 0 40 0;
 0 41 0;]';
M_.nstatic = 17;
M_.nfwrd   = 8;
M_.npred   = 8;
M_.nboth   = 0;
M_.nsfwrd   = 8;
M_.nspred   = 8;
M_.ndynamic   = 16;
M_.dynamic_tmp_nbr = [27; 4; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'investment cost of adjustment' ;
  2 , 'name' , 'extra management cost of buying equity' ;
  3 , 'name' , 'cost of borrowing from foreigners' ;
  4 , 'name' , 'fraction of assets diverted' ;
  5 , 'name' , 'marginal cost, eq. (2)' ;
  6 , 'name' , 'FOC wrt P_{i,t}, eq. (3)' ;
  7 , 'name' , 'domestic output, eq. (4)' ;
  8 , 'name' , 'import to capital share ratio, eq. (5)' ;
  9 , 'name' , 'wage to capital share ratio, eq. (6)' ;
  10 , 'name' , 'law of motion of capital, eq. (7)' ;
  11 , 'name' , 'exports, eq. (8)' ;
  12 , 'name' , 'FOC wrt labour, eq. (9)' ;
  13 , 'name' , 'FOC wrt savings in equity, eq. (10)' ;
  14 , 'name' , 'FOC wrt savings in deposits, eq. (11)' ;
  15 , 'name' , 'FOC wrt investment goods, eq. (12)' ;
  16 , 'name' , 'excess return on capital over home deposits, eq. (17)' ;
  17 , 'name' , 'cost advantage of foreign currency debt over home deposits, eq. (18)' ;
  18 , 'name' , 'marginal cost of deposit, eq. (19)' ;
  19 , 'name' , 'bank leverage multiple, eq. (20)' ;
  20 , 'name' , 'Tobin Q ratio of the bank, eq. (21)' ;
  21 , 'name' , 'fraction of assets financed by foreign borrowing, eq. (22)' ;
  22 , 'name' , 'output, eq. (23)' ;
  23 , 'name' , 'law of motion of net foreign debt, eq. (24)' ;
  24 , 'name' , 'aggregate net worth of banks, eq. (25)' ;
  25 , 'name' , 'aggregate balance sheet of the bank, eq. (26)' ;
  26 , 'name' , 'aggregate balance sheet of the bank, eq. (27)' ;
  27 , 'name' , 'aggregate balance sheet of the bank, eq. (28)' ;
  28 , 'name' , 'aggregate capital, eq. (29)' ;
  29 , 'name' , 'Taylor rule, eq. (30)' ;
  30 , 'name' , 'productivity' ;
  31 , 'name' , 'foreign income' ;
  32 , 'name' , 'foreign interest rate' ;
  33 , 'name' , 'Net output, pg. 21' ;
};
M_.mapping.mc.eqidx = [5 6 ];
M_.mapping.Pi.eqidx = [6 14 16 17 18 22 24 29 33 ];
M_.mapping.Z.eqidx = [5 8 9 13 16 24 ];
M_.mapping.w.eqidx = [5 9 12 ];
M_.mapping.R.eqidx = [14 16 17 18 24 29 ];
M_.mapping.epsilon.eqidx = [5 8 11 17 23 24 26 27 33 ];
M_.mapping.Q.eqidx = [3 13 15 16 24 25 26 27 ];
M_.mapping.Y.eqidx = [6 7 22 33 ];
M_.mapping.M.eqidx = [7 8 23 33 ];
M_.mapping.L.eqidx = [6 7 9 12 13 14 16 17 18 ];
M_.mapping.C.eqidx = [6 13 14 16 17 18 22 ];
M_.mapping.I.eqidx = [1 10 15 22 ];
M_.mapping.K.eqidx = [2 7 8 9 10 13 28 ];
M_.mapping.EX.eqidx = [11 22 23 ];
M_.mapping.N.eqidx = [24 25 26 ];
M_.mapping.K_b.eqidx = [3 24 25 26 27 28 ];
M_.mapping.K_h.eqidx = [2 13 28 ];
M_.mapping.D.eqidx = [24 26 ];
M_.mapping.D_star.eqidx = [23 24 26 27 ];
M_.mapping.x.eqidx = [3 21 25 26 27 ];
M_.mapping.psi.eqidx = [16 17 18 20 ];
M_.mapping.phi.eqidx = [19 20 25 ];
M_.mapping.upsilon.eqidx = [18 19 21 ];
M_.mapping.mu.eqidx = [16 19 ];
M_.mapping.mu_star.eqidx = [17 19 21 ];
M_.mapping.A.eqidx = [5 7 30 ];
M_.mapping.R_star.eqidx = [17 23 24 32 ];
M_.mapping.Y_star.eqidx = [11 31 ];
M_.mapping.Phi.eqidx = [1 15 22 ];
M_.mapping.Theta.eqidx = [4 19 20 ];
M_.mapping.chi_h.eqidx = [2 22 33 ];
M_.mapping.chi_b.eqidx = [3 22 33 ];
M_.mapping.Ynet.eqidx = [33 ];
M_.mapping.varepsilon_R.eqidx = [29 ];
M_.mapping.varepsilon_A.eqidx = [30 ];
M_.mapping.varepsilon_Rstar.eqidx = [32 ];
M_.mapping.varepsilon_Ystar.eqidx = [31 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [5 13 16 18 19 26 27 28 ];
M_.exo_names_orig_ord = [1:4];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(33, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(4, 1);
M_.params = NaN(27, 1);
M_.endo_trends = struct('deflator', cell(33, 1), 'log_deflator', cell(33, 1), 'growth_factor', cell(33, 1), 'log_growth_factor', cell(33, 1));
M_.NNZDerivatives = [168; -1; -1; ];
M_.static_tmp_nbr = [23; 0; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(1) = 0.1;
theta = M_.params(1);
M_.params(2) = 0.399;
theta_0 = M_.params(2);
M_.params(3) = 0.94;
sigma = M_.params(3);
M_.params(4) = 0.0046;
xi = M_.params(4);
M_.params(5) = 0.0219;
varkappa_b = M_.params(5);
M_.params(6) = 0.9852216748768474;
betta = M_.params(6);
M_.params(7) = 0.3333333333333333;
zeta = M_.params(7);
M_.params(8) = 7.883;
zeta_0 = M_.params(8);
M_.params(9) = 0.0197;
varkappa_h = M_.params(9);
M_.params(10) = 0.3;
alphha_K = M_.params(10);
M_.params(11) = 0.18;
alphha_M = M_.params(11);
M_.params(12) = 0.98;
lambda = M_.params(12);
M_.params(13) = 10;
eta = M_.params(13);
M_.params(14) = 0.6666666666666666;
omega = M_.params(14);
M_.params(17) = (M_.params(13)-1)*M_.params(14)/((1-M_.params(14))*(1-M_.params(14)*M_.params(6)));
kappa = M_.params(17);
M_.params(15) = 0.6666666666666666;
kappa_I = M_.params(15);
M_.params(16) = 1;
varphi = M_.params(16);
M_.params(19) = 0.8;
rho_i = M_.params(19);
M_.params(20) = 1.5;
omega_pi = M_.params(20);
M_.params(21) = 0.9;
rho_A = M_.params(21);
M_.params(22) = 0.9;
rho_Rstar = M_.params(22);
M_.params(23) = 0.9;
rho_Ystar = M_.params(23);
M_.params(24) = 0.0025;
sigma_i = M_.params(24);
M_.params(25) = 0.0025;
sigma_istar = M_.params(25);
M_.params(26) = 0.013;
sigma_A = M_.params(26);
M_.params(27) = 0.03;
sigma_Ystar = M_.params(27);
M_.params(18) = 1;
A_ss = M_.params(18);
%
% INITVAL instructions
%
options_.initval_file = false;
oo_.steady_state(1) = 0.900000000000;
oo_.steady_state(2) = 1.000000000000;
oo_.steady_state(3) = 0.040164248783;
oo_.steady_state(4) = 5.217734200796;
oo_.steady_state(5) = 1.015000000000;
oo_.steady_state(6) = 1.000000000000;
oo_.steady_state(7) = 1.000000000000;
oo_.steady_state(8) = 3.233012428123;
oo_.steady_state(9) = 0.523748013356;
oo_.steady_state(10) = 0.289982156648;
oo_.steady_state(11) = 2.208979406695;
oo_.steady_state(12) = 0.434671819865;
oo_.steady_state(13) = 21.733590993261;
oo_.steady_state(14) = 0.564049124591;
oo_.steady_state(15) = 4.030111123462;
oo_.steady_state(13) = 21.733590993261;
oo_.steady_state(16) = 16.120444493847;
oo_.steady_state(17) = 5.613146499414;
oo_.steady_state(18) = 8.047502106154;
oo_.steady_state(19) = 4.030111123462;
oo_.steady_state(20) = 0.250000000000;
oo_.steady_state(21) = 1.596000000000;
oo_.steady_state(22) = 4.000000000000;
oo_.steady_state(23) = 1.560240000000;
oo_.steady_state(24) = 0.007938391646;
oo_.steady_state(25) = 0.007685911330;
oo_.steady_state(26) = 1.000000000000;
oo_.steady_state(28) = 0.564049124591;
oo_.steady_state(27) = 1.010000000000;
oo_.steady_state(22) = 4.000000000000;
oo_.steady_state(30) = 0.399000000000;
oo_.steady_state(31) = 0.014279647772;
oo_.steady_state(32) = 0.011032429200;
oo_.steady_state(33) = 2.683952337795;
oo_.steady_state(29) = 0.000000000000;
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
write_latex_parameter_table;
write_latex_definitions;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
model_diagnostics(M_,options_,oo_);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(3, 3) = (M_.params(25))^2;
options_.TeX = 1;
write_latex_parameter_table;
options_.irf = 80;
options_.order = 1;
var_list_ = {'Ynet';'C';'I';'EX';'M';'D';'D_star';'epsilon';'Q';'N';'Pi';'R'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'ABK2016_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'ABK2016_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'ABK2016_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'ABK2016_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'ABK2016_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'ABK2016_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'ABK2016_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
