%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
clear global
tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'policy_sb';
%
% Some global variables initialization
%
global_initialization;
diary off;
logname_ = 'policy_sb.log';
if exist(logname_, 'file')
    delete(logname_)
end
diary(logname_)
M_.exo_names = 'ea';
M_.exo_names_tex = 'ea';
M_.exo_names = char(M_.exo_names, 'esigma');
M_.exo_names_tex = char(M_.exo_names_tex, 'esigma');
M_.exo_names = char(M_.exo_names, 'efshock');
M_.exo_names_tex = char(M_.exo_names_tex, 'efshock');
M_.exo_names = char(M_.exo_names, 'eai');
M_.exo_names_tex = char(M_.exo_names_tex, 'eai');
M_.endo_names = 'lambda';
M_.endo_names_tex = 'lambda';
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names = char(M_.endo_names, 'h');
M_.endo_names_tex = char(M_.endo_names_tex, 'h');
M_.endo_names = char(M_.endo_names, 'inv');
M_.endo_names_tex = char(M_.endo_names_tex, 'inv');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names = char(M_.endo_names, 'ne');
M_.endo_names_tex = char(M_.endo_names_tex, 'ne');
M_.endo_names = char(M_.endo_names, 'atilde');
M_.endo_names_tex = char(M_.endo_names_tex, 'atilde');
M_.endo_names = char(M_.endo_names, 'b');
M_.endo_names_tex = char(M_.endo_names_tex, 'b');
M_.endo_names = char(M_.endo_names, 'nc');
M_.endo_names_tex = char(M_.endo_names_tex, 'nc');
M_.endo_names = char(M_.endo_names, 'Hc');
M_.endo_names_tex = char(M_.endo_names_tex, 'Hc');
M_.endo_names = char(M_.endo_names, 'bc');
M_.endo_names_tex = char(M_.endo_names_tex, 'bc');
M_.endo_names = char(M_.endo_names, 'Fc');
M_.endo_names_tex = char(M_.endo_names_tex, 'Fc');
M_.endo_names = char(M_.endo_names, 'vc');
M_.endo_names_tex = char(M_.endo_names_tex, 'vc');
M_.endo_names = char(M_.endo_names, 'H1c');
M_.endo_names_tex = char(M_.endo_names_tex, 'H1c');
M_.endo_names = char(M_.endo_names, 'Gc');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gc');
M_.endo_names = char(M_.endo_names, 'omegacbar');
M_.endo_names_tex = char(M_.endo_names_tex, 'omegacbar');
M_.endo_names = char(M_.endo_names, 'rc');
M_.endo_names_tex = char(M_.endo_names_tex, 'rc');
M_.endo_names = char(M_.endo_names, 'G1c');
M_.endo_names_tex = char(M_.endo_names_tex, 'G1c');
M_.endo_names = char(M_.endo_names, 'ns');
M_.endo_names_tex = char(M_.endo_names_tex, 'ns');
M_.endo_names = char(M_.endo_names, 'Hs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Hs');
M_.endo_names = char(M_.endo_names, 'bs');
M_.endo_names_tex = char(M_.endo_names_tex, 'bs');
M_.endo_names = char(M_.endo_names, 'Fs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Fs');
M_.endo_names = char(M_.endo_names, 'vs');
M_.endo_names_tex = char(M_.endo_names_tex, 'vs');
M_.endo_names = char(M_.endo_names, 'H1s');
M_.endo_names_tex = char(M_.endo_names_tex, 'H1s');
M_.endo_names = char(M_.endo_names, 'Gs');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gs');
M_.endo_names = char(M_.endo_names, 'omegasbar');
M_.endo_names_tex = char(M_.endo_names_tex, 'omegasbar');
M_.endo_names = char(M_.endo_names, 'rs');
M_.endo_names_tex = char(M_.endo_names_tex, 'rs');
M_.endo_names = char(M_.endo_names, 'G1s');
M_.endo_names_tex = char(M_.endo_names_tex, 'G1s');
M_.endo_names = char(M_.endo_names, 'dc');
M_.endo_names_tex = char(M_.endo_names_tex, 'dc');
M_.endo_names = char(M_.endo_names, 'kb');
M_.endo_names_tex = char(M_.endo_names_tex, 'kb');
M_.endo_names = char(M_.endo_names, 'rcl');
M_.endo_names_tex = char(M_.endo_names_tex, 'rcl');
M_.endo_names = char(M_.endo_names, 'rsl');
M_.endo_names_tex = char(M_.endo_names_tex, 'rsl');
M_.endo_names = char(M_.endo_names, 'omegacbar1');
M_.endo_names_tex = char(M_.endo_names_tex, 'omegacbar1');
M_.endo_names = char(M_.endo_names, 'vc1');
M_.endo_names_tex = char(M_.endo_names_tex, 'vc1');
M_.endo_names = char(M_.endo_names, 'Fc1');
M_.endo_names_tex = char(M_.endo_names_tex, 'Fc1');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names = char(M_.endo_names, 'rp');
M_.endo_names_tex = char(M_.endo_names_tex, 'rp');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names = char(M_.endo_names, 'rstilde');
M_.endo_names_tex = char(M_.endo_names_tex, 'rstilde');
M_.endo_names = char(M_.endo_names, 'ks');
M_.endo_names_tex = char(M_.endo_names_tex, 'ks');
M_.endo_names = char(M_.endo_names, 'ds');
M_.endo_names_tex = char(M_.endo_names_tex, 'ds');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names = char(M_.endo_names, 'vk');
M_.endo_names_tex = char(M_.endo_names_tex, 'vk');
M_.endo_names = char(M_.endo_names, 'gdp');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdp');
M_.endo_names = char(M_.endo_names, 'sigma');
M_.endo_names_tex = char(M_.endo_names_tex, 'sigma');
M_.endo_names = char(M_.endo_names, 'utility');
M_.endo_names_tex = char(M_.endo_names_tex, 'utility');
M_.endo_names = char(M_.endo_names, 'totutility');
M_.endo_names_tex = char(M_.endo_names_tex, 'totutility');
M_.endo_names = char(M_.endo_names, 'fshock');
M_.endo_names_tex = char(M_.endo_names_tex, 'fshock');
M_.endo_names = char(M_.endo_names, 'ai');
M_.endo_names_tex = char(M_.endo_names_tex, 'ai');
M_.endo_names = char(M_.endo_names, 'bsshare');
M_.endo_names_tex = char(M_.endo_names_tex, 'bsshare');
M_.endo_names = char(M_.endo_names, 'levtot');
M_.endo_names_tex = char(M_.endo_names_tex, 'levtot');
M_.endo_names = char(M_.endo_names, 'levs');
M_.endo_names_tex = char(M_.endo_names_tex, 'levs');
M_.endo_names = char(M_.endo_names, 'levc');
M_.endo_names_tex = char(M_.endo_names_tex, 'levc');
M_.endo_names = char(M_.endo_names, 'car');
M_.endo_names_tex = char(M_.endo_names_tex, 'car');
M_.endo_names = char(M_.endo_names, 'lnb');
M_.endo_names_tex = char(M_.endo_names_tex, 'lnb');
M_.endo_names = char(M_.endo_names, 'zs');
M_.endo_names_tex = char(M_.endo_names_tex, 'zs');
M_.endo_names = char(M_.endo_names, 'zc');
M_.endo_names_tex = char(M_.endo_names_tex, 'zc');
M_.endo_names = char(M_.endo_names, 'lngdp');
M_.endo_names_tex = char(M_.endo_names_tex, 'lngdp');
M_.endo_names = char(M_.endo_names, 'Ftot');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ftot');
M_.endo_names = char(M_.endo_names, 'dcar');
M_.endo_names_tex = char(M_.endo_names_tex, 'dcar');
M_.endo_names = char(M_.endo_names, 'totutility1');
M_.endo_names_tex = char(M_.endo_names_tex, 'totutility1');
M_.param_names = 'BETA';
M_.param_names_tex = 'BETA';
M_.param_names = char(M_.param_names, 'DELTA');
M_.param_names_tex = char(M_.param_names_tex, 'DELTA');
M_.param_names = char(M_.param_names, 'ALPHA');
M_.param_names_tex = char(M_.param_names_tex, 'ALPHA');
M_.param_names = char(M_.param_names, 'CHI');
M_.param_names_tex = char(M_.param_names_tex, 'CHI');
M_.param_names = char(M_.param_names, 'FRISCH');
M_.param_names_tex = char(M_.param_names_tex, 'FRISCH');
M_.param_names = char(M_.param_names, 'INVELAST');
M_.param_names_tex = char(M_.param_names_tex, 'INVELAST');
M_.param_names = char(M_.param_names, 'THETAE');
M_.param_names_tex = char(M_.param_names_tex, 'THETAE');
M_.param_names = char(M_.param_names, 'THETA');
M_.param_names_tex = char(M_.param_names_tex, 'THETA');
M_.param_names = char(M_.param_names, 'PSID');
M_.param_names_tex = char(M_.param_names_tex, 'PSID');
M_.param_names = char(M_.param_names, 'SIGMA');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMA');
M_.param_names = char(M_.param_names, 'THETAC');
M_.param_names_tex = char(M_.param_names_tex, 'THETAC');
M_.param_names = char(M_.param_names, 'TRANSB');
M_.param_names_tex = char(M_.param_names_tex, 'TRANSB');
M_.param_names = char(M_.param_names, 'THETAS');
M_.param_names_tex = char(M_.param_names_tex, 'THETAS');
M_.param_names = char(M_.param_names, 'TRANSS');
M_.param_names_tex = char(M_.param_names_tex, 'TRANSS');
M_.param_names = char(M_.param_names, 'VK');
M_.param_names_tex = char(M_.param_names_tex, 'VK');
M_.param_names = char(M_.param_names, 'DSBS');
M_.param_names_tex = char(M_.param_names_tex, 'DSBS');
M_.param_names = char(M_.param_names, 'GAMMAC');
M_.param_names_tex = char(M_.param_names_tex, 'GAMMAC');
M_.param_names = char(M_.param_names, 'GAMMAS');
M_.param_names_tex = char(M_.param_names_tex, 'GAMMAS');
M_.param_names = char(M_.param_names, 'KAPPAB');
M_.param_names_tex = char(M_.param_names_tex, 'KAPPAB');
M_.param_names = char(M_.param_names, 'GDPSS');
M_.param_names_tex = char(M_.param_names_tex, 'GDPSS');
M_.param_names = char(M_.param_names, 'BSS');
M_.param_names_tex = char(M_.param_names_tex, 'BSS');
M_.param_names = char(M_.param_names, 'BCSS');
M_.param_names_tex = char(M_.param_names_tex, 'BCSS');
M_.param_names = char(M_.param_names, 'RHOA');
M_.param_names_tex = char(M_.param_names_tex, 'RHOA');
M_.param_names = char(M_.param_names, 'RHOS');
M_.param_names_tex = char(M_.param_names_tex, 'RHOS');
M_.param_names = char(M_.param_names, 'RHOF');
M_.param_names_tex = char(M_.param_names_tex, 'RHOF');
M_.param_names = char(M_.param_names, 'RHOAI');
M_.param_names_tex = char(M_.param_names_tex, 'RHOAI');
M_.param_names = char(M_.param_names, 'SIGA');
M_.param_names_tex = char(M_.param_names_tex, 'SIGA');
M_.param_names = char(M_.param_names, 'SIGS');
M_.param_names_tex = char(M_.param_names_tex, 'SIGS');
M_.param_names = char(M_.param_names, 'SIGF');
M_.param_names_tex = char(M_.param_names_tex, 'SIGF');
M_.param_names = char(M_.param_names, 'SIGAI');
M_.param_names_tex = char(M_.param_names_tex, 'SIGAI');
M_.param_names = char(M_.param_names, 'RHOVK');
M_.param_names_tex = char(M_.param_names_tex, 'RHOVK');
M_.param_names = char(M_.param_names, 'MCY');
M_.param_names_tex = char(M_.param_names_tex, 'MCY');
M_.param_names = char(M_.param_names, 'VKY');
M_.param_names_tex = char(M_.param_names_tex, 'VKY');
M_.param_names = char(M_.param_names, 'RCTARGET');
M_.param_names_tex = char(M_.param_names_tex, 'RCTARGET');
M_.param_names = char(M_.param_names, 'CSS');
M_.param_names_tex = char(M_.param_names_tex, 'CSS');
M_.param_names = char(M_.param_names, 'HSS');
M_.param_names_tex = char(M_.param_names_tex, 'HSS');
M_.param_names = char(M_.param_names, 'DCSS');
M_.param_names_tex = char(M_.param_names_tex, 'DCSS');
M_.exo_det_nbr = 0;
M_.exo_nbr = 4;
M_.endo_nbr = 63;
M_.param_nbr = 37;
M_.orig_endo_nbr = 63;
M_.aux_vars = [];
M_.Sigma_e = zeros(4, 4);
M_.H = 0;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('policy_sb_static');
erase_compiled_function('policy_sb_dynamic');
M_.lead_lag_incidence = [
 0 15 78;
 0 16 0;
 0 17 0;
 1 18 79;
 0 19 0;
 2 20 0;
 3 21 0;
 0 22 0;
 0 23 0;
 0 24 0;
 0 25 0;
 4 26 0;
 0 27 0;
 0 28 0;
 0 29 0;
 0 30 0;
 0 31 0;
 0 32 0;
 0 33 0;
 0 34 0;
 0 35 0;
 5 36 0;
 0 37 0;
 0 38 0;
 0 39 0;
 0 40 0;
 0 41 0;
 6 42 0;
 0 43 0;
 0 44 0;
 7 45 0;
 0 46 0;
 0 47 0;
 0 48 0;
 0 49 0;
 0 50 0;
 0 51 0;
 0 52 0;
 0 53 80;
 0 54 81;
 0 55 0;
 8 56 0;
 0 57 0;
 9 58 0;
 10 59 0;
 0 60 0;
 11 61 0;
 0 62 0;
 0 63 82;
 12 64 0;
 13 65 83;
 0 66 0;
 0 67 0;
 0 68 0;
 0 69 0;
 14 70 0;
 0 71 0;
 0 72 0;
 0 73 0;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 84;]';
M_.nstatic = 44;
M_.nfwrd   = 5;
M_.npred   = 12;
M_.nboth   = 2;
M_.equations_tags = {
};
M_.exo_names_orig_ord = [1:4];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(63, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(4, 1);
M_.params = NaN(37, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 258;
M_.NNZDerivatives(2) = 564;
M_.NNZDerivatives(3) = -1;
parameter=cali;
M_.params( 1 ) = parameter(1);
BETA = M_.params( 1 );
M_.params( 2 ) = parameter(2);
DELTA = M_.params( 2 );
M_.params( 3 ) = parameter(3);
ALPHA = M_.params( 3 );
M_.params( 4 ) = parameter(4);
CHI = M_.params( 4 );
M_.params( 5 ) = parameter(5);
FRISCH = M_.params( 5 );
M_.params( 6 ) = parameter(6);
INVELAST = M_.params( 6 );
M_.params( 7 ) = parameter(7);
THETAE = M_.params( 7 );
M_.params( 8 ) = parameter(8);
THETA = M_.params( 8 );
M_.params( 9 ) = parameter(9);
PSID = M_.params( 9 );
M_.params( 10 ) = parameter(10);
SIGMA = M_.params( 10 );
M_.params( 11 ) = parameter(11);
THETAC = M_.params( 11 );
M_.params( 12 ) = parameter(12);
TRANSB = M_.params( 12 );
M_.params( 15 ) = parameter(13);
VK = M_.params( 15 );
M_.params( 17 ) = parameter(14);
GAMMAC = M_.params( 17 );
M_.params( 18 ) = parameter(15);
GAMMAS = M_.params( 18 );
M_.params( 19 ) = parameter(16);
KAPPAB = M_.params( 19 );
M_.params( 34 ) = parameter(17);
RCTARGET = M_.params( 34 );
M_.params( 13 ) = parameter(18);
THETAS = M_.params( 13 );
M_.params( 14 ) = parameter(19);
TRANSS = M_.params( 14 );
M_.params( 16 ) = parameter(20);
DSBS = M_.params( 16 );
M_.params( 20 ) = solvegdp(M_.params(1),M_.params(2),M_.params(3),M_.params(7),M_.params(8),M_.params(34),M_.params(10),M_.params(16),M_.params(15),M_.params(17),M_.params(18),M_.params(19),M_.params(4),M_.params(5));
GDPSS = M_.params( 20 );
M_.params( 21 ) = solveb(M_.params(1),M_.params(2),M_.params(3),M_.params(7),M_.params(8),M_.params(34),M_.params(10),M_.params(16),M_.params(15),M_.params(17),M_.params(18),M_.params(19),M_.params(4),M_.params(5));
BSS = M_.params( 21 );
M_.params( 22 ) = 1;
BCSS = M_.params( 22 );
M_.params( 35 ) = solvec(M_.params(1),M_.params(2),M_.params(3),M_.params(7),M_.params(8),M_.params(34),M_.params(10),M_.params(16),M_.params(15),M_.params(17),M_.params(18),M_.params(19),M_.params(4),M_.params(5));
CSS = M_.params( 35 );
M_.params( 36 ) = solveh(M_.params(1),M_.params(2),M_.params(3),M_.params(7),M_.params(8),M_.params(34),M_.params(10),M_.params(16),M_.params(15),M_.params(17),M_.params(18),M_.params(19),M_.params(4),M_.params(5));
HSS = M_.params( 36 );
M_.params( 37 ) = solvedc(M_.params(1),M_.params(2),M_.params(3),M_.params(7),M_.params(8),M_.params(34),M_.params(10),M_.params(16),M_.params(15),M_.params(17),M_.params(18),M_.params(19),M_.params(4),M_.params(5));
DCSS = M_.params( 37 );
M_.params( 23 ) = 0.95;
RHOA = M_.params( 23 );
M_.params( 24 ) = 0.97;
RHOS = M_.params( 24 );
M_.params( 26 ) = 0.91;
RHOAI = M_.params( 26 );
M_.params( 25 ) = 0.82;
RHOF = M_.params( 25 );
M_.params( 27 ) = 0.01;
SIGA = M_.params( 27 );
M_.params( 28 ) = 0.01;
SIGS = M_.params( 28 );
M_.params( 30 ) = 0.0;
SIGAI = M_.params( 30 );
M_.params( 29 ) = 0.0;
SIGF = M_.params( 29 );
M_.params( 31 ) = 0;
RHOVK = M_.params( 31 );
M_.params( 32 ) = 0;
MCY = M_.params( 32 );
M_.params( 33 ) = 0;
VKY = M_.params( 33 );
load calishock;
M_.params( 27 ) = SIG(1);
SIGA = M_.params( 27 );
M_.params( 28 ) = SIG(2);
SIGS = M_.params( 28 );
steady;
resid;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = M_.params(27)^2;
M_.Sigma_e(2, 2) = M_.params(28)^2;
M_.Sigma_e(3, 3) = M_.params(29)^2;
M_.Sigma_e(4, 4) = M_.params(30)^2;
M_.sigma_e_is_diagonal = 1;
options_.irf = 40;
options_.nograph = 1;
options_.noprint = 1;
options_.order = 2;
var_list_=[];
info = stoch_simul(var_list_);
save('policy_sb_results.mat', 'oo_', 'M_', 'options_');


disp(['Total computing time : ' dynsec2hms(toc) ]);
diary off
