function [ys_, params, info] = policy_sb_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    [ys_(1),ys_(2),ys_(3),ys_(4),ys_(5),ys_(6),ys_(7),ys_(8),ys_(9),ys_(10),ys_(11),ys_(12),ys_(13),ys_(14),ys_(15),ys_(16),ys_(17),ys_(18),ys_(19),ys_(20),ys_(21),ys_(22),ys_(23),ys_(24),ys_(25),ys_(26),ys_(27),ys_(28),ys_(29),ys_(30),ys_(31),ys_(32),ys_(33),ys_(37),ys_(38),ys_(39),ys_(40),ys_(44),ys_(45),ys_(46),ys_(47),ys_(48),ys_(49),ys_(50),ys_(51),ys_(34),ys_(35),ys_(36),ys_(41)]=solvess_rc(params(1),params(2),params(3),params(7),params(8),params(34),params(10),params(16),params(15),params(17),params(18),params(19),params(4),params(5));
    ys_(43)=params(16)*ys_(22);
    ys_(42)=ys_(22)-ys_(43);
    ys_(52)=ys_(22)/(ys_(12)+ys_(22));
    ys_(53)=(ys_(12)+ys_(22))/(ys_(10)+ys_(20));
    ys_(54)=ys_(22)/ys_(20);
    ys_(55)=ys_(12)/ys_(10);
    ys_(56)=1/ys_(45);
    ys_(57)=log(ys_(9));
    ys_(58)=ys_(8)*ys_(27)*(1+ys_(20)/ys_(22));
    ys_(59)=ys_(8)*ys_(17)*(1+ys_(10)/ys_(12));
    ys_(60)=log(ys_(46));
    ys_(61)=(ys_(12)*ys_(13)+ys_(22)*ys_(23))/(ys_(12)+ys_(22));
    ys_(63)=(log(ys_(2))-params(4)*ys_(3)^(1+params(5))/(1+params(5)))/(1-params(1));
    % Auxiliary equations
    check_=0;
end
