%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'bench_nosb';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('bench_nosb.log');
M_.exo_names = 'ea';
M_.exo_names_tex = 'ea';
M_.exo_names_long = 'ea';
M_.exo_names = char(M_.exo_names, 'esigma');
M_.exo_names_tex = char(M_.exo_names_tex, 'esigma');
M_.exo_names_long = char(M_.exo_names_long, 'esigma');
M_.exo_names = char(M_.exo_names, 'efshock');
M_.exo_names_tex = char(M_.exo_names_tex, 'efshock');
M_.exo_names_long = char(M_.exo_names_long, 'efshock');
M_.exo_names = char(M_.exo_names, 'eai');
M_.exo_names_tex = char(M_.exo_names_tex, 'eai');
M_.exo_names_long = char(M_.exo_names_long, 'eai');
M_.exo_names = char(M_.exo_names, 'evk');
M_.exo_names_tex = char(M_.exo_names_tex, 'evk');
M_.exo_names_long = char(M_.exo_names_long, 'evk');
M_.endo_names = 'lambda';
M_.endo_names_tex = 'lambda';
M_.endo_names_long = 'lambda';
M_.endo_names = char(M_.endo_names, 'c');
M_.endo_names_tex = char(M_.endo_names_tex, 'c');
M_.endo_names_long = char(M_.endo_names_long, 'c');
M_.endo_names = char(M_.endo_names, 'h');
M_.endo_names_tex = char(M_.endo_names_tex, 'h');
M_.endo_names_long = char(M_.endo_names_long, 'h');
M_.endo_names = char(M_.endo_names, 'inv');
M_.endo_names_tex = char(M_.endo_names_tex, 'inv');
M_.endo_names_long = char(M_.endo_names_long, 'inv');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'ne');
M_.endo_names_tex = char(M_.endo_names_tex, 'ne');
M_.endo_names_long = char(M_.endo_names_long, 'ne');
M_.endo_names = char(M_.endo_names, 'atilde');
M_.endo_names_tex = char(M_.endo_names_tex, 'atilde');
M_.endo_names_long = char(M_.endo_names_long, 'atilde');
M_.endo_names = char(M_.endo_names, 'b');
M_.endo_names_tex = char(M_.endo_names_tex, 'b');
M_.endo_names_long = char(M_.endo_names_long, 'b');
M_.endo_names = char(M_.endo_names, 'nc');
M_.endo_names_tex = char(M_.endo_names_tex, 'nc');
M_.endo_names_long = char(M_.endo_names_long, 'nc');
M_.endo_names = char(M_.endo_names, 'Hc');
M_.endo_names_tex = char(M_.endo_names_tex, 'Hc');
M_.endo_names_long = char(M_.endo_names_long, 'Hc');
M_.endo_names = char(M_.endo_names, 'bc');
M_.endo_names_tex = char(M_.endo_names_tex, 'bc');
M_.endo_names_long = char(M_.endo_names_long, 'bc');
M_.endo_names = char(M_.endo_names, 'Fc');
M_.endo_names_tex = char(M_.endo_names_tex, 'Fc');
M_.endo_names_long = char(M_.endo_names_long, 'Fc');
M_.endo_names = char(M_.endo_names, 'vc');
M_.endo_names_tex = char(M_.endo_names_tex, 'vc');
M_.endo_names_long = char(M_.endo_names_long, 'vc');
M_.endo_names = char(M_.endo_names, 'H1c');
M_.endo_names_tex = char(M_.endo_names_tex, 'H1c');
M_.endo_names_long = char(M_.endo_names_long, 'H1c');
M_.endo_names = char(M_.endo_names, 'Gc');
M_.endo_names_tex = char(M_.endo_names_tex, 'Gc');
M_.endo_names_long = char(M_.endo_names_long, 'Gc');
M_.endo_names = char(M_.endo_names, 'omegacbar');
M_.endo_names_tex = char(M_.endo_names_tex, 'omegacbar');
M_.endo_names_long = char(M_.endo_names_long, 'omegacbar');
M_.endo_names = char(M_.endo_names, 'rc');
M_.endo_names_tex = char(M_.endo_names_tex, 'rc');
M_.endo_names_long = char(M_.endo_names_long, 'rc');
M_.endo_names = char(M_.endo_names, 'G1c');
M_.endo_names_tex = char(M_.endo_names_tex, 'G1c');
M_.endo_names_long = char(M_.endo_names_long, 'G1c');
M_.endo_names = char(M_.endo_names, 'dc');
M_.endo_names_tex = char(M_.endo_names_tex, 'dc');
M_.endo_names_long = char(M_.endo_names_long, 'dc');
M_.endo_names = char(M_.endo_names, 'kb');
M_.endo_names_tex = char(M_.endo_names_tex, 'kb');
M_.endo_names_long = char(M_.endo_names_long, 'kb');
M_.endo_names = char(M_.endo_names, 'rcl');
M_.endo_names_tex = char(M_.endo_names_tex, 'rcl');
M_.endo_names_long = char(M_.endo_names_long, 'rcl');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'rp');
M_.endo_names_tex = char(M_.endo_names_tex, 'rp');
M_.endo_names_long = char(M_.endo_names_long, 'rp');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'rk');
M_.endo_names_tex = char(M_.endo_names_tex, 'rk');
M_.endo_names_long = char(M_.endo_names_long, 'rk');
M_.endo_names = char(M_.endo_names, 'a');
M_.endo_names_tex = char(M_.endo_names_tex, 'a');
M_.endo_names_long = char(M_.endo_names_long, 'a');
M_.endo_names = char(M_.endo_names, 'vk');
M_.endo_names_tex = char(M_.endo_names_tex, 'vk');
M_.endo_names_long = char(M_.endo_names_long, 'vk');
M_.endo_names = char(M_.endo_names, 'gdp');
M_.endo_names_tex = char(M_.endo_names_tex, 'gdp');
M_.endo_names_long = char(M_.endo_names_long, 'gdp');
M_.endo_names = char(M_.endo_names, 'sigma');
M_.endo_names_tex = char(M_.endo_names_tex, 'sigma');
M_.endo_names_long = char(M_.endo_names_long, 'sigma');
M_.endo_names = char(M_.endo_names, 'utility');
M_.endo_names_tex = char(M_.endo_names_tex, 'utility');
M_.endo_names_long = char(M_.endo_names_long, 'utility');
M_.endo_names = char(M_.endo_names, 'totutility');
M_.endo_names_tex = char(M_.endo_names_tex, 'totutility');
M_.endo_names_long = char(M_.endo_names_long, 'totutility');
M_.endo_names = char(M_.endo_names, 'fshock');
M_.endo_names_tex = char(M_.endo_names_tex, 'fshock');
M_.endo_names_long = char(M_.endo_names_long, 'fshock');
M_.endo_names = char(M_.endo_names, 'ai');
M_.endo_names_tex = char(M_.endo_names_tex, 'ai');
M_.endo_names_long = char(M_.endo_names_long, 'ai');
M_.endo_names = char(M_.endo_names, 'levc');
M_.endo_names_tex = char(M_.endo_names_tex, 'levc');
M_.endo_names_long = char(M_.endo_names_long, 'levc');
M_.endo_names = char(M_.endo_names, 'levtot');
M_.endo_names_tex = char(M_.endo_names_tex, 'levtot');
M_.endo_names_long = char(M_.endo_names_long, 'levtot');
M_.endo_names = char(M_.endo_names, 'car');
M_.endo_names_tex = char(M_.endo_names_tex, 'car');
M_.endo_names_long = char(M_.endo_names_long, 'car');
M_.endo_names = char(M_.endo_names, 'lnb');
M_.endo_names_tex = char(M_.endo_names_tex, 'lnb');
M_.endo_names_long = char(M_.endo_names_long, 'lnb');
M_.endo_names = char(M_.endo_names, 'zc');
M_.endo_names_tex = char(M_.endo_names_tex, 'zc');
M_.endo_names_long = char(M_.endo_names_long, 'zc');
M_.endo_names = char(M_.endo_names, 'lngdp');
M_.endo_names_tex = char(M_.endo_names_tex, 'lngdp');
M_.endo_names_long = char(M_.endo_names_long, 'lngdp');
M_.endo_names = char(M_.endo_names, 'Ftot');
M_.endo_names_tex = char(M_.endo_names_tex, 'Ftot');
M_.endo_names_long = char(M_.endo_names_long, 'Ftot');
M_.param_names = 'BETA';
M_.param_names_tex = 'BETA';
M_.param_names_long = 'BETA';
M_.param_names = char(M_.param_names, 'DELTA');
M_.param_names_tex = char(M_.param_names_tex, 'DELTA');
M_.param_names_long = char(M_.param_names_long, 'DELTA');
M_.param_names = char(M_.param_names, 'ALPHA');
M_.param_names_tex = char(M_.param_names_tex, 'ALPHA');
M_.param_names_long = char(M_.param_names_long, 'ALPHA');
M_.param_names = char(M_.param_names, 'CHI');
M_.param_names_tex = char(M_.param_names_tex, 'CHI');
M_.param_names_long = char(M_.param_names_long, 'CHI');
M_.param_names = char(M_.param_names, 'FRISCH');
M_.param_names_tex = char(M_.param_names_tex, 'FRISCH');
M_.param_names_long = char(M_.param_names_long, 'FRISCH');
M_.param_names = char(M_.param_names, 'INVELAST');
M_.param_names_tex = char(M_.param_names_tex, 'INVELAST');
M_.param_names_long = char(M_.param_names_long, 'INVELAST');
M_.param_names = char(M_.param_names, 'THETAE');
M_.param_names_tex = char(M_.param_names_tex, 'THETAE');
M_.param_names_long = char(M_.param_names_long, 'THETAE');
M_.param_names = char(M_.param_names, 'THETA');
M_.param_names_tex = char(M_.param_names_tex, 'THETA');
M_.param_names_long = char(M_.param_names_long, 'THETA');
M_.param_names = char(M_.param_names, 'PSID');
M_.param_names_tex = char(M_.param_names_tex, 'PSID');
M_.param_names_long = char(M_.param_names_long, 'PSID');
M_.param_names = char(M_.param_names, 'SIGMA');
M_.param_names_tex = char(M_.param_names_tex, 'SIGMA');
M_.param_names_long = char(M_.param_names_long, 'SIGMA');
M_.param_names = char(M_.param_names, 'THETAC');
M_.param_names_tex = char(M_.param_names_tex, 'THETAC');
M_.param_names_long = char(M_.param_names_long, 'THETAC');
M_.param_names = char(M_.param_names, 'TRANSB');
M_.param_names_tex = char(M_.param_names_tex, 'TRANSB');
M_.param_names_long = char(M_.param_names_long, 'TRANSB');
M_.param_names = char(M_.param_names, 'VK');
M_.param_names_tex = char(M_.param_names_tex, 'VK');
M_.param_names_long = char(M_.param_names_long, 'VK');
M_.param_names = char(M_.param_names, 'GAMMAC');
M_.param_names_tex = char(M_.param_names_tex, 'GAMMAC');
M_.param_names_long = char(M_.param_names_long, 'GAMMAC');
M_.param_names = char(M_.param_names, 'GAMMAS');
M_.param_names_tex = char(M_.param_names_tex, 'GAMMAS');
M_.param_names_long = char(M_.param_names_long, 'GAMMAS');
M_.param_names = char(M_.param_names, 'KAPPAB');
M_.param_names_tex = char(M_.param_names_tex, 'KAPPAB');
M_.param_names_long = char(M_.param_names_long, 'KAPPAB');
M_.param_names = char(M_.param_names, 'GDPSS');
M_.param_names_tex = char(M_.param_names_tex, 'GDPSS');
M_.param_names_long = char(M_.param_names_long, 'GDPSS');
M_.param_names = char(M_.param_names, 'RHOA');
M_.param_names_tex = char(M_.param_names_tex, 'RHOA');
M_.param_names_long = char(M_.param_names_long, 'RHOA');
M_.param_names = char(M_.param_names, 'RHOS');
M_.param_names_tex = char(M_.param_names_tex, 'RHOS');
M_.param_names_long = char(M_.param_names_long, 'RHOS');
M_.param_names = char(M_.param_names, 'RHOF');
M_.param_names_tex = char(M_.param_names_tex, 'RHOF');
M_.param_names_long = char(M_.param_names_long, 'RHOF');
M_.param_names = char(M_.param_names, 'RHOAI');
M_.param_names_tex = char(M_.param_names_tex, 'RHOAI');
M_.param_names_long = char(M_.param_names_long, 'RHOAI');
M_.param_names = char(M_.param_names, 'SIGA');
M_.param_names_tex = char(M_.param_names_tex, 'SIGA');
M_.param_names_long = char(M_.param_names_long, 'SIGA');
M_.param_names = char(M_.param_names, 'SIGS');
M_.param_names_tex = char(M_.param_names_tex, 'SIGS');
M_.param_names_long = char(M_.param_names_long, 'SIGS');
M_.param_names = char(M_.param_names, 'SIGF');
M_.param_names_tex = char(M_.param_names_tex, 'SIGF');
M_.param_names_long = char(M_.param_names_long, 'SIGF');
M_.param_names = char(M_.param_names, 'SIGAI');
M_.param_names_tex = char(M_.param_names_tex, 'SIGAI');
M_.param_names_long = char(M_.param_names_long, 'SIGAI');
M_.param_names = char(M_.param_names, 'RHOVK');
M_.param_names_tex = char(M_.param_names_tex, 'RHOVK');
M_.param_names_long = char(M_.param_names_long, 'RHOVK');
M_.param_names = char(M_.param_names, 'MCY');
M_.param_names_tex = char(M_.param_names_tex, 'MCY');
M_.param_names_long = char(M_.param_names_long, 'MCY');
M_.param_names = char(M_.param_names, 'VKY');
M_.param_names_tex = char(M_.param_names_tex, 'VKY');
M_.param_names_long = char(M_.param_names_long, 'VKY');
M_.param_names = char(M_.param_names, 'RCTARGET');
M_.param_names_tex = char(M_.param_names_tex, 'RCTARGET');
M_.param_names_long = char(M_.param_names_long, 'RCTARGET');
M_.exo_det_nbr = 0;
M_.exo_nbr = 5;
M_.endo_nbr = 41;
M_.param_nbr = 29;
M_.orig_endo_nbr = 41;
M_.aux_vars = [];
M_.Sigma_e = zeros(5, 5);
M_.Correlation_matrix = eye(5, 5);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('bench_nosb_static');
erase_compiled_function('bench_nosb_dynamic');
M_.lead_lag_incidence = [
 0 11 52;
 0 12 0;
 0 13 0;
 1 14 53;
 0 15 0;
 2 16 0;
 3 17 0;
 0 18 0;
 0 19 0;
 0 20 0;
 0 21 0;
 4 22 0;
 0 23 0;
 0 24 0;
 0 25 0;
 0 26 0;
 0 27 0;
 0 28 0;
 0 29 0;
 0 30 0;
 5 31 0;
 0 32 0;
 0 33 0;
 0 34 0;
 0 35 54;
 0 36 55;
 6 37 0;
 7 38 0;
 0 39 0;
 8 40 0;
 0 41 0;
 0 42 56;
 9 43 0;
 10 44 57;
 0 45 0;
 0 46 0;
 0 47 0;
 0 48 0;
 0 49 0;
 0 50 0;
 0 51 0;]';
M_.nstatic = 27;
M_.nfwrd   = 4;
M_.npred   = 8;
M_.nboth   = 2;
M_.nsfwrd   = 6;
M_.nspred   = 10;
M_.ndynamic   = 14;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:5];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(41, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(5, 1);
M_.params = NaN(29, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 153;
M_.NNZDerivatives(2) = -1;
M_.NNZDerivatives(3) = -1;
parameter=cali;
M_.params( 1 ) = parameter(1);
BETA = M_.params( 1 );
M_.params( 2 ) = parameter(2);
DELTA = M_.params( 2 );
M_.params( 3 ) = parameter(3);
ALPHA = M_.params( 3 );
M_.params( 4 ) = parameter(4);
CHI = M_.params( 4 );
M_.params( 5 ) = parameter(5);
FRISCH = M_.params( 5 );
M_.params( 6 ) = parameter(6);
INVELAST = M_.params( 6 );
M_.params( 7 ) = parameter(7);
THETAE = M_.params( 7 );
M_.params( 8 ) = parameter(8);
THETA = M_.params( 8 );
M_.params( 9 ) = parameter(9);
PSID = M_.params( 9 );
M_.params( 10 ) = parameter(10);
SIGMA = M_.params( 10 );
M_.params( 11 ) = parameter(11);
THETAC = M_.params( 11 );
M_.params( 12 ) = parameter(12);
TRANSB = M_.params( 12 );
M_.params( 13 ) = parameter(13);
VK = M_.params( 13 );
M_.params( 14 ) = parameter(14);
GAMMAC = M_.params( 14 );
M_.params( 15 ) = parameter(15);
GAMMAS = M_.params( 15 );
M_.params( 16 ) = parameter(16);
KAPPAB = M_.params( 16 );
M_.params( 29 ) = parameter(17);
RCTARGET = M_.params( 29 );
M_.params( 12 ) = solvetransb_nosb(M_.params(1),M_.params(2),M_.params(3),M_.params(7),M_.params(8),M_.params(9),M_.params(10),M_.params(11),M_.params(13),M_.params(14),M_.params(16));
TRANSB = M_.params( 12 );
M_.params( 17 ) = solvegdp_nosb(M_.params(1),M_.params(2),M_.params(3),M_.params(7),M_.params(8),M_.params(9),M_.params(10),M_.params(11),M_.params(13),M_.params(14),M_.params(16),M_.params(4),M_.params(5));
GDPSS = M_.params( 17 );
M_.params( 18 ) = 0.95;
RHOA = M_.params( 18 );
M_.params( 19 ) = 0.98;
RHOS = M_.params( 19 );
M_.params( 21 ) = 0.91;
RHOAI = M_.params( 21 );
M_.params( 20 ) = 0.82;
RHOF = M_.params( 20 );
M_.params( 22 ) = 0.01;
SIGA = M_.params( 22 );
M_.params( 23 ) = 0.01;
SIGS = M_.params( 23 );
M_.params( 25 ) = 0.0;
SIGAI = M_.params( 25 );
M_.params( 24 ) = 0.0;
SIGF = M_.params( 24 );
M_.params( 26 ) = 0;
RHOVK = M_.params( 26 );
M_.params( 27 ) = 0;
MCY = M_.params( 27 );
M_.params( 28 ) = 0;
VKY = M_.params( 28 );
steady;
resid;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = M_.params(22)^2;
M_.Sigma_e(2, 2) = M_.params(23)^2;
M_.Sigma_e(3, 3) = M_.params(24)^2;
M_.Sigma_e(4, 4) = M_.params(25)^2;
M_.Sigma_e(5, 5) = 0.0001;
options_.irf = 40;
options_.nograph = 1;
options_.order = 1;
options_.irf_shocks=[];
options_.irf_shocks = 'evk';
var_list_=[];
info = stoch_simul(var_list_);
save('bench_nosb_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('bench_nosb_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('bench_nosb_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('bench_nosb_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('bench_nosb_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
