% Run this file to replicate Table 2 - 3, Figure 2-5. 
% Before running this file, you need to input information on the type of the shock and the type of economy by changing codes in line 6 and 7. 

%% Choose shock type and economy type
clear
shock = 2; % 1 for technology shock % 2 for risk shock
sepa  = 0; % 0 for benchmark case % 1 for segmented credit market 
if shock == 1
    SIG = [0.01 0];
end
if shock == 2
    SIG = [0 0.01];
end
save calishock SIG sepa shock

%% Calculates the optimal policy coefficients that maximize the unconditional welfare
opt_rule; 

%% Display results
plot_irfs_opt;     % generate the impulse responses shown in Figure 2-5 using respolicy_X.mat that saves optimal policy coefficients and welfare results, generated by opt_rule.m

display_opt_rule; % generate the data in Table 2-3 using respolicy_X.mat that saves optimal policy coefficients and welfare results, generated by opt_rule.m


