% Run this file to replicate Table  A1. 
% Before running this file, you need to input information on the type of the shock by changing codes in line 6. 

%% Choose shock type and economy type
clear
shock = 1; % 1 for technology shock % 2 for risk shock
sepa  = 0; % 0 for benchmark case
if shock == 1
    SIG = [0.01 0];
end
if shock == 2
    SIG = [0 0.01];
end
save calishock SIG sepa shock

%% Calculates the optimal policy coefficients that maximize the conditional welfare
opt_rule_cond; 

%% Display results

display_opt_rule_cond; % generate the data in Table A1 using respolicy_X_cond.mat that saves optimal policy coefficients and welfare results, generated by opt_rule_cond.m


